### ISSUE TITLE
Scoping viewmodels with dagger2?

### ISSUE THREAD

**Issue by ghost** [hansenji/ViewModelInject#7]
Been using this library for a while and it's great! But since this library doesn't require you to explicitly define providers for the viewmodels, how can I make it such that I can apply/un-apply a scope for the viewmodel?

**Comment by hansenji** [comment]
ViewModels are scoped to the activity/fragment/nav graph they are associated with. They shouldn't be scoped via Dagger. If you are wanting to do dagger scoping I would recommend using something other than a ViewModel
